application: rants
version: 1
runtime: go
api_version: go1

handlers:
- url: /COPYING$
  mime_type: text/plain
  static_files: COPYING
  upload: COPYING$

- url: /favicon\.ico$
  static_files: static/favicon.ico
  upload: static/favicon\.ico$

- url: /README\.md$
  mime_type: text/plain
  static_files: README.md
  upload: README\.md$

- url: /robots\.txt$
  static_files: static/robots.txt
  upload: static/robots\.txt$

- url: /signify\.pub$
  mime_type: text/plain
  static_files: static/signify.pub
  upload: static/signify\.pub$

- url: /static
  static_dir: static

- url: /(v1/.*)?$
  script: _go_app
